# Generated by Django 4.2.6 on 2023-10-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='expense_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
